import Head from "next/head";
import styles from "../styles/Home.module.css";
import Icons from "../components/iconslist";
import Search from "../components/search";
import IconsData from "../components/icons.json";
// import * as React from "react";
import React, { useState } from "react";

export default function Home() {
  const [checked, setChecked] = useState(false);
  const handleChange = () => {
    setChecked(!checked);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Standartio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* icons */}
      {/* <Icons ratio={checked ? 2 : 1} /> */}
      <Search IconsData={IconsData} />
      {/* Size toggle */}
    </div>
  );
}
